Replace Poetry Based Project Configuration with setuptools
stiebels/sagemaker-rightline pull request #20
Opened 2023-05-29 18:02 UTC by dipanjank

Fixes #7 (partly)

# Proposed Changes

- Replace poetry related configuration in pyproject.toml with [PEP 518 supported configuration elements](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) understood by pip.
- Change the CI/CD workflow to "pip install" the dependencies. 
- Move the pre-commit check in CI/CD to its own job.
- Add a simple PR template.

# Maintenance

* [ ] Updated tests
* [ ] Updated documentation

2023-05-30 15:22 UTC, stiebels commented on pyproject.toml
> +    {name = "stiebels", email = "stiebels@github.com"}
Feel free to add your alias here as well

2023-05-30 15:33 UTC, stiebels requested changes
Few minor change requests

2023-06-02 16:17 UTC, dipanjank commented on pyproject.toml
> +[project.urls]  # Optional
Fixed.

2023-06-02 16:19 UTC, dipanjank commented on .github/workflows/python-package.yml
>      - name: Pre-Commit
Fixed.

2023-06-02 16:19 UTC, dipanjank commented on pyproject.toml
> +    {name = "stiebels", email = "stiebels@github.com"}
Done.

2023-06-03 21:15 UTC, stiebels approved these changes

2023-06-03 21:15 UTC, merged